// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB86BaJIMQVv5B8t-pzMrONgjf6wdYIHCM',
    appId: '1:957742934687:web:95a174e4cd57edbedf50aa',
    messagingSenderId: '957742934687',
    projectId: 'griho-sheba',
    authDomain: 'griho-sheba.firebaseapp.com',
    databaseURL: 'https://griho-sheba-default-rtdb.firebaseio.com',
    storageBucket: 'griho-sheba.appspot.com',
    measurementId: 'G-XN7S0MKKJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJeyw3FbA_6VzaOnHBN7NKtEcK4C6CIQc',
    appId: '1:957742934687:android:4d351e1c4b4027f5df50aa',
    messagingSenderId: '957742934687',
    projectId: 'griho-sheba',
    databaseURL: 'https://griho-sheba-default-rtdb.firebaseio.com',
    storageBucket: 'griho-sheba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7bY1Yd18k-BlMVloPahTIZ_YTskYJiFg',
    appId: '1:957742934687:ios:00b037ba80910c1fdf50aa',
    messagingSenderId: '957742934687',
    projectId: 'griho-sheba',
    databaseURL: 'https://griho-sheba-default-rtdb.firebaseio.com',
    storageBucket: 'griho-sheba.appspot.com',
    iosClientId: '957742934687-4r2qh4t43ts924eg4cvcbs41cstgr57s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGrihoSheba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7bY1Yd18k-BlMVloPahTIZ_YTskYJiFg',
    appId: '1:957742934687:ios:00b037ba80910c1fdf50aa',
    messagingSenderId: '957742934687',
    projectId: 'griho-sheba',
    databaseURL: 'https://griho-sheba-default-rtdb.firebaseio.com',
    storageBucket: 'griho-sheba.appspot.com',
    iosClientId: '957742934687-4r2qh4t43ts924eg4cvcbs41cstgr57s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterGrihoSheba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB86BaJIMQVv5B8t-pzMrONgjf6wdYIHCM',
    appId: '1:957742934687:web:8ac4446c6e6f5b7bdf50aa',
    messagingSenderId: '957742934687',
    projectId: 'griho-sheba',
    authDomain: 'griho-sheba.firebaseapp.com',
    databaseURL: 'https://griho-sheba-default-rtdb.firebaseio.com',
    storageBucket: 'griho-sheba.appspot.com',
    measurementId: 'G-CWCHP29YT9',
  );

}